const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSquadData: (seasonId) => ipcRenderer.invoke('get-squad-data', seasonId),
  getSeasonsList: () => ipcRenderer.invoke('get-seasons-list'),
  getAllTimeSquad: () => ipcRenderer.invoke('get-all-time-squad'),
  getPastPlayers: () => ipcRenderer.invoke('get-past-players'),
  getPlayerHistory: (playerId) => ipcRenderer.invoke('get-player-history', playerId),
  triggerRefresh: () => ipcRenderer.invoke('trigger-refresh'),
  getCareerTotals: () => ipcRenderer.invoke('get-career-totals'),
  getManagerPPG: () => ipcRenderer.invoke('get-manager-ppg'),
  getTeamRecordSeasons: () => ipcRenderer.invoke('get-team-record-seasons'),
  getInferredTransfers: (saveId) => ipcRenderer.invoke('get-inferred-transfers', saveId),
  getTransferFees: (saveId) => ipcRenderer.invoke('get-transfer-fees', saveId),
  getPlayerTransferHistory: (playerId, saveId) => ipcRenderer.invoke('get-player-transfer-history', playerId, saveId),
  getSavesList: () => ipcRenderer.invoke('get-saves-list'),
  selectSave: (saveId) => ipcRenderer.invoke('select-save', saveId),
  deleteSave: (saveId) => ipcRenderer.invoke('delete-save', saveId),
  deletePlayer: (playerId) => ipcRenderer.invoke('delete-player', playerId),
  getSeasonCompetitionResults: (seasonId) => ipcRenderer.invoke('get-season-competition-results', seasonId),
  getTrophiesWon: () => ipcRenderer.invoke('get-trophies-won'),
  getYouthAcademy: (saveId) => ipcRenderer.invoke('get-youth-academy', saveId),
  enableYouthMode: (saveId) => ipcRenderer.invoke('enable-youth-mode', saveId),
  clearFormerPlayers: (saveId) => ipcRenderer.invoke('clear-former-players', saveId),
  getPendingSeasonReview: (saveId) => ipcRenderer.invoke('get-pending-season-review', saveId),
  getPlayerHonours: (playerId, saveId) => ipcRenderer.invoke('get-player-honours', playerId, saveId),
  acknowledgeSeasonReview: (reviewId) => ipcRenderer.invoke('acknowledge-season-review', reviewId),
  getLeagueStatsForSeason: (seasonId) => ipcRenderer.invoke('get-league-stats-for-season', seasonId),
  getSignedPlayers: (saveId) => ipcRenderer.invoke('get-signed-players', saveId),
  markAcademyGraduate: (playerId, saveId) => ipcRenderer.invoke('mark-academy-graduate', playerId, saveId),
  getPendingSeasonOverview: (saveId) => ipcRenderer.invoke('get-pending-season-overview', saveId),
  acknowledgeSeasonOverview: (saveId, seasonId) => ipcRenderer.invoke('acknowledge-season-overview', saveId, seasonId),
  getSeasonOverviewPreview: (saveId) => ipcRenderer.invoke('get-season-overview-preview', saveId),
  exportSeasonOverviewPdf: (suggestedFileName) => ipcRenderer.invoke('export-season-overview-pdf', suggestedFileName),
  getSeasonAlerts: (saveId) => ipcRenderer.invoke('get-season-alerts', saveId),
  dismissMayReminder: (saveId, seasonId) => ipcRenderer.invoke('dismiss-may-reminder', saveId, seasonId),

  onSquadUpdated: (callback) => ipcRenderer.on('squad-updated', (_event, data) => callback(data)),
  onCareerStatsUpdated: (callback) => ipcRenderer.on('career-stats-updated', (_event, data) => callback(data)),
  onTransfersUpdated: (callback) => ipcRenderer.on('transfers-updated', (_event, data) => callback(data)),
  onCalendarUpdated: (callback) => ipcRenderer.on('calendar-updated', (_event, data) => callback(data)),
  onYouthUpdated: (callback) => ipcRenderer.on('youth-updated', (_event, data) => callback(data)),
  onLeagueStatsUpdated: (callback) => ipcRenderer.on('league-stats-updated', (_event, data) => callback(data))
});