const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getSquadData: (seasonId) => ipcRenderer.invoke('get-squad-data', seasonId),
  getSeasonsList: () => ipcRenderer.invoke('get-seasons-list'),
  getAllTimeSquad: () => ipcRenderer.invoke('get-all-time-squad'),
  getPastPlayers: () => ipcRenderer.invoke('get-past-players'),
  getPlayerHistory: (playerId) => ipcRenderer.invoke('get-player-history', playerId),
  triggerRefresh: () => ipcRenderer.invoke('trigger-refresh'),
  getCareerTotals: () => ipcRenderer.invoke('get-career-totals'),
  getManagerPPG: () => ipcRenderer.invoke('get-manager-ppg'),
  getTeamRecordSeasons: () => ipcRenderer.invoke('get-team-record-seasons'),
  getInferredTransfers: (saveId) => ipcRenderer.invoke('get-inferred-transfers', saveId),
  getTransferFees: (saveId) => ipcRenderer.invoke('get-transfer-fees', saveId),
  getPlayerTransferHistory: (playerId, saveId) => ipcRenderer.invoke('get-player-transfer-history', playerId, saveId),
  getPlayerInjuryHistory: (playerId, saveId) => ipcRenderer.invoke('get-player-injury-history', playerId, saveId),
  getInjuryReport: (saveId) => ipcRenderer.invoke('get-injury-report', saveId),
  setInjuryEpisodeType: (episodeId, injuryTypeId) => ipcRenderer.invoke('set-injury-episode-type', episodeId, injuryTypeId),
  returnPlayerToFullFitness: (episodeId, endDate) => ipcRenderer.invoke('return-player-to-full-fitness', episodeId, endDate),
  markPlayerCurrentlyInjured: (playerId, startDate, injuryTypeId, saveId) => ipcRenderer.invoke('mark-player-currently-injured', playerId, startDate, injuryTypeId, saveId),
  deleteInjuryEpisode: (episodeId) => ipcRenderer.invoke('delete-injury-episode', episodeId),
  updateInjuryEpisode: (episodeId, startDate, endDate, injuryTypeId) => ipcRenderer.invoke('update-injury-episode', episodeId, startDate, endDate, injuryTypeId),
  getPlayerContractRenewal: (playerId, saveId) => ipcRenderer.invoke('get-player-contract-renewal', playerId, saveId),
  getSavesList: () => ipcRenderer.invoke('get-saves-list'),
  selectSave: (saveId) => ipcRenderer.invoke('select-save', saveId),
  deleteSave: (saveId) => ipcRenderer.invoke('delete-save', saveId),
  deletePlayer: (playerId) => ipcRenderer.invoke('delete-player', playerId),
  getSeasonCompetitionResults: (seasonId) => ipcRenderer.invoke('get-season-competition-results', seasonId),
  getTrophiesWon: () => ipcRenderer.invoke('get-trophies-won'),
  getYouthAcademy: (saveId) => ipcRenderer.invoke('get-youth-academy', saveId),
  enableYouthMode: (saveId) => ipcRenderer.invoke('enable-youth-mode', saveId),
  clearFormerPlayers: (saveId) => ipcRenderer.invoke('clear-former-players', saveId),
  getPendingSeasonReview: (saveId) => ipcRenderer.invoke('get-pending-season-review', saveId),
  getPlayerHonours: (playerId, saveId) => ipcRenderer.invoke('get-player-honours', playerId, saveId),
  getPlayerMotmTally: (playerId, saveId, yearLabel) => ipcRenderer.invoke('get-player-motm-tally', playerId, saveId, yearLabel),
  acknowledgeSeasonReview: (reviewId) => ipcRenderer.invoke('acknowledge-season-review', reviewId),
  getLeagueStatsForSeason: (seasonId) => ipcRenderer.invoke('get-league-stats-for-season', seasonId),
  getSeasonStandings: (seasonId) => ipcRenderer.invoke('get-season-standings', seasonId),
  getWorldLeagueSeasons: (saveId) => ipcRenderer.invoke('get-world-league-seasons', saveId),
  getWorldLeagueAwardsForSeason: (seasonLabel, saveId) => ipcRenderer.invoke('get-world-league-awards-for-season', seasonLabel, saveId),
  getSignedPlayers: (saveId) => ipcRenderer.invoke('get-signed-players', saveId),
  getCurrentCaptaincy: (saveId, role) => ipcRenderer.invoke('get-current-captaincy', saveId, role),
  getCaptaincyHistoryForPlayer: (saveId, playerId, role) => ipcRenderer.invoke('get-captaincy-history-for-player', saveId, playerId, role),
  setCaptaincy: (saveId, role, playerId, inGameYear) => ipcRenderer.invoke('set-captaincy', saveId, role, playerId, inGameYear),
  setCaptaincyStartYear: (saveId, role, playerId, startYear) => ipcRenderer.invoke('set-captaincy-start-year', saveId, role, playerId, startYear),
  markAcademyGraduate: (playerId, saveId) => ipcRenderer.invoke('mark-academy-graduate', playerId, saveId),
  getManualPlayStyles: (playerId) => ipcRenderer.invoke('get-manual-play-styles', playerId),
  setManualPlayStyles: (playerId, styles) => ipcRenderer.invoke('set-manual-play-styles', playerId, styles),
  getHeadshotBucketOptions: () => ipcRenderer.invoke('get-headshot-bucket-options'),
  getHeadshotFilesForBucket: (ageDir, ethnicityDir) => ipcRenderer.invoke('get-headshot-files-for-bucket', ageDir, ethnicityDir),
  getPlayerHeadshotBucket: (playerId) => ipcRenderer.invoke('get-player-headshot-bucket', playerId),
  setManualHeadshot: (playerId, headshotPath) => ipcRenderer.invoke('set-manual-headshot', playerId, headshotPath),
  clearManualHeadshot: (playerId) => ipcRenderer.invoke('clear-manual-headshot', playerId),
  getUntouchablePlayerIds: (saveId) => ipcRenderer.invoke('get-untouchable-player-ids', saveId),
  setPlayerUntouchable: (saveId, playerId, untouchable) => ipcRenderer.invoke('set-player-untouchable', saveId, playerId, untouchable),
  getPendingSeasonOverview: (saveId) => ipcRenderer.invoke('get-pending-season-overview', saveId),
  acknowledgeSeasonOverview: (saveId, seasonId) => ipcRenderer.invoke('acknowledge-season-overview', saveId, seasonId),
  getSeasonOverviewPreview: (saveId) => ipcRenderer.invoke('get-season-overview-preview', saveId),
  exportSeasonOverviewPdf: (suggestedFileName) => ipcRenderer.invoke('export-season-overview-pdf', suggestedFileName),
  getSeasonAlerts: (saveId) => ipcRenderer.invoke('get-season-alerts', saveId),
  dismissMayReminder: (saveId, seasonId) => ipcRenderer.invoke('dismiss-may-reminder', saveId, seasonId),

  connectedCareerStatus: () => ipcRenderer.invoke('connected-career-status'),
  connectedCareerJoin: (code, owner) => ipcRenderer.invoke('connected-career-join', code, owner),
  connectedCareerSyncNow: () => ipcRenderer.invoke('connected-career-sync-now'),
  connectedCareerLeave: () => ipcRenderer.invoke('connected-career-leave'),
  connectedCareerExportSquadForMirroring: () => ipcRenderer.invoke('connected-career-export-squad-for-mirroring'),
  connectedCareerPushFullRows: () => ipcRenderer.invoke('connected-career-push-full-rows'),
  connectedCareerPullMirrorCreates: () => ipcRenderer.invoke('connected-career-pull-mirror-creates'),
  connectedCareerConfirmMirrorResults: () => ipcRenderer.invoke('connected-career-confirm-mirror-results'),

  onSquadUpdated: (callback) => ipcRenderer.on('squad-updated', (_event, data) => callback(data)),
  onCareerStatsUpdated: (callback) => ipcRenderer.on('career-stats-updated', (_event, data) => callback(data)),
  onTransfersUpdated: (callback) => ipcRenderer.on('transfers-updated', (_event, data) => callback(data)),
  onCalendarUpdated: (callback) => ipcRenderer.on('calendar-updated', (_event, data) => callback(data)),
  onYouthUpdated: (callback) => ipcRenderer.on('youth-updated', (_event, data) => callback(data)),
  onLeagueStatsUpdated: (callback) => ipcRenderer.on('league-stats-updated', (_event, data) => callback(data))
});